### ISSUE TITLE
Fix copyright as this is an infringement of the license

### ISSUE THREAD

**Issue by LithyRiolu** [uPlexa/uplexa#16]
It seems you have replace all instances of @Monero-Project for uPlexa in every file and this is an infringement of [Monero's codebase license](https://github.com/monero-project/monero/blob/master/LICENSE). By replacing the license, you have broken the copyright laws.

***

### Solution to resolve issue
```cpp
// Copyright (c) 2018, uPlexa Team
//
// 
// All rights reserved.
// ...
```
should be replaced to
```cpp
// Copyright (c) 2018, uPlexa Team
// Copyright (c) 2014-2019, The Monero Project
// 
// All rights reserved.
// ...
```

*I would also update the year as you possibly have up-streamed Monero commits*.

**Comment by QuantumLeaper** [comment]
Hi @LithyRiolu 
Thank you very much for bringing up this issue.

I have since made the changes you have suggested as per commits:
28c19026047e7847cc1d6ec026763a727526a99f
2ca5eadc25a640aa3a973ca06434bf7f9da20905

Cheers!

**Comment by jtgrassie** [comment]
As I understand it, you also cannot simply claim copyright for code you have not touched. There are many files you haven't touched, other than adding your copyright claim on them.

**Comment by QuantumLeaper** [comment]
Thanks @jtgrassie that was something I was unaware of. I apologize on behalf of the developers of uPlexa for making such changes. 
I have gone ahead and removed all uPlexa Copyright claims from all files in which were not modified by the uPlexa team:
e1e25cb6ea25f75115c1e020a052221b1f0bf4ee
