### ISSUE TITLE
EOF on stdin, exiting

### ISSUE THREAD

**Issue by wmoreno3** [uPlexa/uplexa#5]
Hello, I'm trying to boot `uplexad` from the start in Ubuntu Server 18.04, but it stops because the following comes up in the log `7fc078b52700 INFO global contrib / epee / include / console_handler.h: 359 EOF on stdin, exiting`
Note: On terminal `#ExecStart=/bin/bash /usr/local/bin/uplexa.sh` runs ready.
My scripts:

```
# cat /usr/local/bin/uplexa.sh
#!/bin/bash
/root/mineria/uplexa-command-linux64/uplexad
```

And
```
# cat /etc/systemd/system/uplexa.service
[Unit]
Description=uplexad
After=network.target

[Service]
ExecStart=/bin/bash /usr/local/bin/uplexa.sh
Type=oneshot
RemainAfterExit=true

[Install]
WantedBy=default.target
```

**Comment by uPlexa** [comment]
Hi there,
Is this the pre-compiled release or a version you have compiled yourself?

**Comment by wmoreno3** [comment]
Thanks for answer.
I used `https://github.com/uPlexa/uplexa/releases/download/v0.2.0.0/uplexa-command-linux64-v0.2.0.0.tar.bz2`

**Comment by wmoreno3** [comment]
I was guided by `monerod.service`: [](https://github.com/monero-project/monero/blob/master/utils/systemd/monerod.service) and it worked `uplexad` at start up.

```
root@server:~# cat /usr/local/bin/uplexa.sh
#!/bin/bash
/root/mineria/uplexa-command-linux64/uplexad --non-interactive --detach
root@server:~# cat /etc/systemd/system/uplexa.service
[Unit]
Description=Uplexa Full Node
After=network.target

[Service]
WorkingDirectory=/root/mineria/uplexa-command-linux64/

Type=forking
ExecStart=/bin/bash /usr/local/bin/uplexa.sh

Restart=always

[Install]
WantedBy=multi-user.target
root@server:~#
```
