### ISSUE TITLE
Boost_VERSION VERSION_LESS 106200 returns true even when version is newer than requested

### ISSUE THREAD

**Issue by 03vmate** [uPlexa/uplexa#69]
In CMakeLists.txt:888, the check for Boost version 1.62 or higher returns true even with a newer version:

`
-- Found Boost Version: 1.71.0
CMake Error at CMakeLists.txt:889 (message):
  Boost older than 1.62 is too old to link with OpenSSL 1.1 or newer.  Update
  Boost or install OpenSSL 1.0 and set path to it when running cmake: cmake
  -DOPENSSL_ROOT_DIR='/usr/include/openssl-1.0;/usr/lib/openssl-1.0'
`

Code snippet from CMakeLists.txt:
`
message(STATUS "Found Boost Version: ${Boost_VERSION}")
  if (Boost_VERSION VERSION_LESS 106200 AND NOT (OPENSSL_VERSION VERSION_LESS 1.1))
      message(FATAL_ERROR "Boost older than 1.62 is too old to link with OpenSSL 1.1 or newer. "
                          "Update Boost or install OpenSSL 1.0 and set path to it when running cmake: "
                          "cmake -DOPENSSL_ROOT_DIR='/usr/include/openssl-1.0;/usr/lib/openssl-1.0'")
`
Using Ubuntu Server 20.04 with cmake 3.16.3-1ubuntu1

**Comment by QuantumLeaper** [comment]
Fixed as per #71
